'use strict';
/* Takt – all tekst som vises i appen, ordnet etter hvor den vises.
   Bokmål med felleskjønn (-en) for hankjønn og hunkjønn.
   Tekster som tar inn verdier, er små funksjoner. */
const plural = (n, one, many) => n + ' ' + (n === 1 ? one : many);

const T = {
  date: {
    wd: ['søndag', 'mandag', 'tirsdag', 'onsdag', 'torsdag', 'fredag', 'lørdag'],
    wdShort: ['ma', 'ti', 'on', 'to', 'fr', 'lø', 'sø'],
    mo: ['januar', 'februar', 'mars', 'april', 'mai', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'desember'],
    moShort: ['jan.', 'feb.', 'mars', 'apr.', 'mai', 'juni', 'juli', 'aug.', 'sep.', 'okt.', 'nov.', 'des.'],
    today: 'i dag', tomorrow: 'i morgen', yesterday: 'i går', nextDayShort: '(neste dag)',
    week: n => 'uke ' + n,
  },
  unit: { min: 'min', hour: 't' },
  common: {
    back: 'Tilbake', close: 'Lukk', save: 'Lagre', saved: 'Lagret', undo: 'Angre', undone: l => 'Angret' + (l ? ': ' + l.charAt(0).toLowerCase() + l.slice(1) : ''),
    nothingToUndo: 'Ingenting å angre', from: 'Fra', to: 'Til', yesDelete: 'Ja, slett', moreInfo: 'Mer forklaring',
    notSaved: 'kan ikke lagre på telefonen',
  },
  top: { prev: 'Forrige dag', next: 'Neste dag', pickDay: 'Velg dag i kalenderen' },
  nav: { label: 'Hovedmeny', today: 'I dag', month: 'Måned', addAria: 'Nytt notat, gjøremål eller avtale', more: 'Mer' },
  file: {
    notTakt: 'Filen er ikke en backup fra Takt.', newer: 'Filen er fra en nyere versjon av Takt. Oppdater appen først.',
    rescued: 'Lagrede data kunne ikke leses. En kopi er tatt vare på, og appen har startet på nytt.',
  },

  shift: {
    title: 'Vakt', weekAria: 'Uken', editAria: 'Endre vakten denne dagen',
    noRota: 'Ingen turnus ennå. Importer turnusen som PDF, så vises vaktene her.', importRota: 'Importer turnus',
    times: (s, e, meet) => s + '–' + e + ' · møt ' + meet, noTimes: 'Vakten mangler tider', noShiftHint: 'Ingen vakt i turnusen',
    changed: 'endret',
    sheetTitle: d => 'Vakt ' + d.charAt(0).toLowerCase() + d.slice(1),
    importedWas: c => 'I turnusen: ' + c, reset: 'Tilbake til turnusen', resetDone: 'Tilbake til turnusen',
    pickCode: 'Velg vakt', noCodes: 'Ingen vaktkoder ennå. Legg dem inn under Vaktkoder, eller importer turnusen.',
    noShift: 'Ingen vakt denne dagen',
    custom: 'Egne tider', customHint: 'For en byttet vakt eller et kurs som bare gjelder denne dagen.',
    customName: 'Navn', customPh: 'Kurs', useCustom: 'Bruk egne tider',
    set: c => 'Vakten er satt til ' + c, cleared: 'Ingen vakt denne dagen', customSet: 'Egne tider er satt',
  },
  away: {
    line: (a, b) => 'Borte ' + a + '–' + b,
    chosen: 'valgt reise', partly: 'delvis valgt reise',
    estimated: set => set ? 'beregnet med din reisetid' : 'beregnet med raskeste reise',
  },

  travel: {
    title: 'Reise', toWork: to => 'Til ' + to, home: 'Hjem', change: 'Endre sted',
    arriveBy: (t, m) => 'Fram senest ' + t + ' (' + m + ' min før vakten)',
    leaveAfter: (t, m, next) => 'Fra ' + t + (next ? ' i morgen' : '') + ' (' + m + ' min etter vakten)',
    loading: 'Henter reiser …', failed: 'Fikk ikke kontakt med reiseplanleggeren.', noTrips: 'Fant ingen reiser som passer.',
    needPlaces: 'Legg inn hjem og arbeidssted, så vises reisene til og fra vakten.', setPlaces: 'Legg inn steder',
    fetched: t => 'Oppdatert ' + t, offline: t => 'Uten nett – viser reiser hentet ' + t, refresh: 'Oppdater',
    arrShort: t => 'fram ' + t, arrive: t => 'hjemme ' + t, slack: m => m + ' min å gå på', onTime: 'akkurat i tide',
    late: m => m + ' min forsinket', early: m => m + ' min tidlig', cancelled: 'innstilt',
    walkMin: m => m + ' min gange', pick: 'Velg', picked: 'Valgt', more: n => 'Flere reiser (' + n + ')', fewer: 'Færre reiser',
    mode: { bus: 'Buss', tram: 'Bybane', rail: 'Tog', water: 'Båt', coach: 'Buss', metro: 'T-bane' },
    badLines: 'Skriv linjenumrene, for eksempel 16E eller 1 + 5.', favExists: 'Den finnes allerede.',
  },
  trip: {
    title: (a, b) => a + ' → ' + b, summary: (m, w) => fmtDur(m) + ' totalt, ' + fmtDur(w) + ' gange',
    walk: (m, to) => 'Gå ' + m + ' min til ' + to, ride: (dest, from, to, m) => 'mot ' + dest + ', fra ' + from + ' til ' + to + ' (' + m + ' min)',
    arrive: 'Framme',
    pickHint: 'En valgt reise gjelder bare denne dagen. Den brukes til å regne ut når du er borte, og vises i Døgn om du deler.',
    pick: 'Velg denne reisen', unpick: 'Fjern valget', pickedToast: 'Reisen er valgt for dagen', unpicked: 'Valget er fjernet',
    saveFav: 'Lagre linjene som favoritt', favSaved: s => s + ' er lagret som favoritt',
  },
  places: {
    title: 'Steder og reise', places: 'Steder',
    role: { home: 'Hjem', work: 'Arbeidssted', none: 'Annet' },
    addRole: { home: 'Legg inn hjem', work: 'Legg inn arbeidssted' }, addOther: 'Nytt sted',
    name: 'Navn', namePh: 'For eksempel Hjem eller Haukeland', address: 'Adresse eller sted', searchPh: 'Søk etter adresse',
    here: 'Bruk der jeg er nå',
    hereHint: 'Står du ved inngangen du bruker, blir gangtiden mest riktig. Telefonen spør om tillatelse til å bruke posisjonen.',
    chosen: l => 'Valgt: ' + l, notChosen: 'Ikke valgt ennå',
    note: 'Merknad', notePh: 'For eksempel avdeling og etasje',
    needAddress: 'Velg en adresse fra søket, eller bruk der du er nå.', searchFailed: 'Søket virket ikke. Prøv igjen når du har nett.',
    noGps: 'Fikk ikke tak i posisjonen.',
    delete: 'Slett stedet', deleteQ: 'Dager som bruker stedet, går tilbake til hjem og arbeidssted.', deleted: 'Stedet er slettet',
    timing: 'Tid rundt vakten', before: 'Min før vakten', after: 'Min etter vakten',
    timingHint: 'Før: når du må være på jobb før vakten starter. Etter: tid til å skifte før du går hjem.',
    oneWay: 'Reisetid én vei (min)', fastestPh: m => 'raskeste: ' + m,
    oneWayHint: 'Brukes til å regne ut når du er borte de dagene du ikke har valgt en reise. Står feltet tomt, brukes den raskeste reisen Takt har funnet.',
    walk: 'Ganghastighet', walkSpeed: { slow: 'Rolig', normal: 'Vanlig', fast: 'Rask' },
    favs: 'Favorittlinjer', favHint: 'Favorittene vises først, i denne rekkefølgen. Lagre en fra en reise, eller skriv linjenumrene.',
    favPh: 'For eksempel 16E eller 1 + 5', favAdd: 'Legg til', favAdded: 'Favoritten er lagt til', favRemoved: 'Favoritten er fjernet',
    favUp: n => 'Flytt ' + n + ' opp', favRemove: n => 'Fjern ' + n,
    dayTitle: d => 'Steder ' + d.charAt(0).toLowerCase() + d.slice(1), dayHint: 'Gjelder bare denne dagen, for eksempel et kurs et annet sted.',
    from: 'Reiser fra', to: 'Reiser til', manage: 'Endre steder', daySaved: 'Stedene for dagen er lagret',
  },

  home: {
    title: 'Hjemme', kids: 'barna', and: ' og ', dognDefault: 'Døgn',
    allAsleep: (w, t) => w + ' sover · siden ' + t,
    someAsleep: (who, t, awake) => who + ' sover (siden ' + t + ')' + (awake ? ', ' + awake + ' er våken' : ''),
    nowUntil: (b, t) => b + ' · til ' + t,
    dinner: 'Middag', youEat: 'du spiser med', youDont: 'uten deg',
    sick: names => 'Syk: ' + names,
    updated: t => 'fra Døgn ' + t, noData: n => 'Ingen oversikt fra ' + n + ' ennå.', noDay: 'Døgn har ingen plan for denne dagen.',
  },

  items: {
    title: 'Notater og gjøremål', add: '+ Ny', empty: 'Ingenting for denne dagen.',
    kind: { todo: 'Gjøremål', appt: 'Avtale', note: 'Notat', shop: 'Handle' },
    kindShort: { appt: 'avtale', note: 'notat', shop: 'kjøp:' },
    titleLabel: { todo: 'Hva skal gjøres', appt: 'Hva', note: 'Notat', shop: 'Hva skal kjøpes' },
    newTitle: 'Nytt', editTitle: 'Endre', date: 'Dag', time: 'Klokkeslett', note: 'Mer tekst',
    dateHint: 'Uten dag vises gjøremål og handling i dag til de er gjort.',
    shareWith: n => 'Del med ' + n, shareHint: 'Delte punkter vises i Døgn. Handling havner på handlelisten der.',
    shared: 'delt', doneInDogn: 'gjort i Døgn',
    needTitle: 'Skriv hva det gjelder.', added: 'Lagt til', deleted: 'Slettet',
    delete: 'Slett', deleteQ: 'Slette dette punktet?',
    checkAria: t => 'Gjort: ' + t,
  },

  cal: { prev: 'Forrige måned', next: 'Neste måned', today: 'I dag', wk: 'u.', hint: 'Fargen viser vakten: dag, kveld, natt eller fri. Prikk: notat, gjøremål eller avtale.' },

  rota: {
    title: 'Turnus', intro: 'Importer turnusen som PDF. Takt leser planen og viser hva den fant, før noe lagres.',
    sourceInfo: (a, b, when) => 'Turnus fra ' + a + ' til ' + b + (when ? ', importert ' + when : '') + '.',
    importPdf: 'Importer turnus (PDF)', importPdfMeta: 'Kalenderplan fra GAT, også skannet',
    importFile: 'Importer turnusfil', importFileMeta: 'Fra Takt, Døgn eller tekst',
    exportFile: 'Del turnusfil', exportMeta: 'Til kolleger eller Døgn', exportName: d => 'takt-turnus-' + d + '.json',
    codesTitle: 'Vaktkoder', codeCount: n => plural(n, 'kode', 'koder'),
    codesHint: 'Tidene brukes til reiser og til å regne ut når du er borte. En vakt som slutter før den starter, varer til neste dag.',
    noCodesYet: 'Ingen koder ennå. De kommer med når turnusen importeres.',
    newCode: 'Ny vaktkode', editCode: c => 'Vaktkode ' + c, code: 'Kode', label: 'Navn', labelPh: 'For eksempel dagvakt',
    kind: { work: 'Vakt', night: 'Natt', off: 'Fri' },
    nightHint: 'Natt: vakten slutter neste morgen.',
    uses: n => plural(n, 'dag', 'dager'), deleteCode: 'Slett koden', deleteQ: n => n ? 'Koden brukes ' + plural(n, 'dag', 'dager') + '. De dagene får ingen vakt.' : 'Koden brukes ikke.',
    codeDeleted: c => c + ' er slettet',
    badCode: 'Koden kan ha opptil 12 bokstaver og tall.', codeExists: c => c + ' finnes allerede.', needTimes: 'Fyll inn når vakten starter og slutter.',
    none: 'Ingen vakt', off: 'fri', customLabel: 'Egne tider', emptyLabel: 'Fri',
    notRota: 'Filen kunne ikke leses som turnus.', noLines: 'Fant ingen dager med vaktkode.',
    reading: 'Leser turnusen', readingHint: 'Planen leses på telefonen. Ingenting sendes noe sted.',
    step: { render: 'Åpner PDF-en …', table: 'Finner tabellen …', ocr: 'Leser vaktene …' },
    pdfNoTable: 'Fant ikke tabellen med uker og dager. Er det kalenderplanen fra GAT?',
    pdfNoDates: 'Fant ikke datoene i første kolonne.', pdfFailed: 'PDF-en kunne ikke leses.',
    reviewTitle: 'Kontroller turnusen',
    found: (n, a, b) => plural(n, 'dag', 'dager') + ' fra ' + a + ' til ' + b,
    checkThese: n => 'Se over ' + plural(n, 'rute', 'ruter'),
    checkHint: 'Disse var vanskelige å lese. Sammenlign med bildet og rett koden om den er feil.',
    imgAlt: 'Ruten i planen', codeFor: d => 'Kode ' + d,
    codesFound: 'Koder i planen', codesFoundHint: 'Bildene er rutene fra planen. Skriv en annen kode for å rette alle rutene i gruppen.',
    codesFileHint: 'Skriv en annen kode for å endre alle dagene med koden.',
    days: n => plural(n, 'dag', 'dager'), newTag: 'ny',
    period: 'Periode', fromDate: 'Ta med fra', toDate: 'Til',
    keepManual: 'Behold dager jeg har endret selv', keepHint: 'Ellers erstatter den nye turnusen også endringene du har gjort for hånd i perioden.',
    publish: 'Publiser', published: n => 'Turnusen er oppdatert (' + plural(n, 'dag', 'dager') + ')',
    badCodeIn: c => '«' + c + '» er ikke en gyldig kode.', needDef: c => 'Fyll inn tider for den nye koden ' + c + '.',
  },

  menu: {
    title: 'Mer', undo: 'Angre', file: 'Backup til fil',
    exportBackup: 'Eksporter backup', exportMeta: 'Lagre en fil med alle dataene', backupName: d => 'takt-backup-' + d + '.json',
    importBackup: 'Importer backup', importMeta: 'Erstatter det som ligger i appen', imported: 'Backupen er hentet inn',
    optional: 'Valgfritt', version: v => 'Takt ' + v,
  },
  profile: {
    title: 'Profil og visning', meta: t => t, name: 'Ditt navn', namePh: 'Valgfritt',
    dognName: 'Navnet til den som bruker Døgn', dognNameHint: 'Brukes bare i tekster, for eksempel «Del med Lars».',
    theme: 'Tema', themes: { auto: 'Følg telefonen', light: 'Lyst', dark: 'Mørkt' },
    textSize: 'Tekststørrelse', sizes: ['Vanlig', 'Større', 'Størst'],
  },
  sync: {
    title: 'Backup og deling med Døgn', off: 'Av', connectedTo: r => 'Koblet til ' + r,
    intro: 'Valgfritt. Med et privat GitHub-repo tas det backup av Takt, turnusen og det du deler sendes til Døgn, og dagen hjemme hentes fra Døgn. Veiledning står i README på GitHub.',
    owner: 'GitHub-brukernavn', repo: 'Repo', token: 'Tilgangsnøkkel',
    tokenHint: 'Nøkkelen lagres bare på denne telefonen, og kommer aldri med i backup eller deling.',
    connect: 'Koble til', publicWarn: 'Repoet er offentlig. Gjør det privat på GitHub.',
    optBackup: 'Backup av Takt', optShare: 'Del turnus, fravær og delte punkter med Døgn', optDogn: 'Hent dagen hjemme fra Døgn',
    lastBackup: 'Siste backup', lastShare: 'Sist delt', lastPull: 'Sist hentet', never: 'aldri',
    filesHint: 'Filene i repoet: takt-backup.json, takt-deling.json og dogn-deling.json.',
    now: 'Oppdater nå', done: 'Oppdatert', restore: 'Hent backup fra GitHub',
    restoreQ: 'Erstatte det som ligger i Takt med backupen fra GitHub?', restored: 'Backupen er hentet inn',
    disconnect: 'Koble fra', disconnectHint: 'Nøkkelen slettes fra telefonen. Filene i repoet blir liggende.',
    commitMsg: p => 'Takt: ' + p,
    noContact: 'Fikk ikke kontakt med GitHub.', unknown: 'Noe gikk galt.',
    errors: { 401: 'Nøkkelen er ugyldig eller utløpt.', 403: 'Nøkkelen mangler tilgang til repoet.', 404: 'Fant ikke repoet. Sjekk navn og tilgang.', 409: 'Filen ble endret samtidig. Prøv igjen.', 422: 'GitHub godtok ikke filen.' },
    errCode: c => 'GitHub svarte med feil ' + c + '.',
    noBackup: 'Fant ingen backup fra Takt i repoet.', noDognFile: 'Fant ingen oversikt fra Døgn i repoet ennå.', notDogn: 'Filen fra Døgn kunne ikke leses.',
  },
  setup: {
    welcome: 'Velkommen til Takt', stepOf: (a, b) => 'Steg ' + a + ' av ' + b,
    intro: 'Takt samler turnusen, reisen til og fra jobb og det du vil huske, dag for dag. Alt lagres på telefonen.',
    haveData: 'Har du brukt Takt før?', fromGithub: 'Hent fra GitHub', next: 'Neste', later: 'Senere',
    placesTitle: 'Hjem og jobb', placesHint: 'Med hjem og arbeidssted finner Takt reisene med Skyss, med gange til og fra holdeplassene.',
    rotaTitle: 'Turnus', rotaHint: 'Importer turnusen som PDF nå, eller senere under Mer › Turnus.',
  },
};
